Get streambed admin
plotly/dokku-acl pull request #1
Opened 2019-05-27 20:38 UTC by BRONSOLO

Dokku-acl related changes needed for https://github.com/plotly/streambed/issues/11790. 

This PR checks against the auth server to determine if a user is an admin and bypasses the acl files if so. 

@scjody or @josegonzalez please review.

2019-05-27 20:46 UTC, BRONSOLO commented
**A few notes:** 

- This repo will be made public and will be referenced when installing the dokku-acl plugin here: https://github.com/plotly/dash-deployment-server/blob/master/Dockerfile#L76

- This implementation queries the auth server directly instead of querying DDS, which would then in turn query the auth server.

2019-05-28 14:42 UTC, scjody commented on pre-build
> +( $DIR/query_admin_status "$PLOTLY_DASH_SECRET_KEY" "$PLOTLY_STREAMBED_IP" "$SSH_NAME" ) && exit 0
The Dokku idiom here is `$PLUGIN_AVAILABLE_PATH/dokku-acl/query_admin_status`.

Also this is more of a 🐄 but Dokku normally uses dashes in command names rather than underscores.

2019-05-28 14:46 UTC, scjody commented on query_admin_status
> +IS_ADMIN="$( curl -k --header "X-Plotly-Dash-Secret-Key: $1" "https://$2/v2/users/$3/" | grep -ci '"is_admin":true' )"
Can we use `jq`here instead of grepping the JSON output?

If not would it be reasonable to use `grep -q` so you can check the exit status directly?

2019-05-28 14:49 UTC, scjody requested changes
Would it be reasonable to add a BATS 🐅 of the new functionality?

2019-05-29 15:53 UTC, josegonzalez commented on pre-build
> +( $DIR/query_admin_status "$PLOTLY_DASH_SECRET_KEY" "$PLOTLY_STREAMBED_IP" "$SSH_NAME" ) && exit 0
Well having a file called `query_admin_status` would normally be fine but that's more for plugin triggers, not for arbitrary functions. What we should do is:

- wrap the body in a function (call it `fn-query-admin-status`) as appropriate
- move the function to the `internal-functions` file
- ensure that file is sourced where the function might otherwise be used
- change the execution to a function call

Happy to chat/slack call to clarify the pattern @BRONSOLO .

2019-06-14 01:39 UTC, BRONSOLO commented
@josegonzalez updates made. Please review!

2019-06-14 17:52 UTC, scjody approved these changes
💃

2019-06-14 17:53 UTC, merged